networks:
  telegram_generation_photo_bot:

version: '3.9'
services:

  redis:
    image: redis:alpine
    env_file:
      - ./.env
    restart: on-failure
    ports:
      - "6579:6379"
    networks:
      - telegram_generation_photo_bot
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    restart: always
    depends_on:
      - redis
    ports:
      - "8011:8080"
    networks:
      - telegram_generation_photo_bot
